language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 firefox
  - sudo a2enmod php5
  - sudo service apache2 restart
  - sudo rm -rf /var/www
  - sudo ln -fs $(pwd) /var/www
  - curl "http://localhost:80/templates/index.php"
  - cd /var/www
  - ls
install: "pip install -r tests/stable-req.txt"
script:  "py.test -s tests/test_basic.py"